"""update Actor schema

Revision ID: a166ede3fb24
Revises: d056e4766481
Create Date: 2020-08-17 21:02:08.704462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a166ede3fb24'
down_revision = 'd056e4766481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'image')
    op.drop_column('actors', 'bio')
    # ### end Alembic commands ###
